<?php
define('_ADMIN_PREFIX_URL','admin');
define('_IMG_CATE_W',1200);
define('_IMG_CATE_THUM_W',220);
define('_IMG_CATE_THUM_H',220);
define('_SLUG_IMG_NAME','zen-to-gel-online-casino');
define('_IMG_DEFAULT','images/thumb-350.png');
define('_UPLOAD_DIRE','uploads/');
define('_DIRE_IS_MONTH',date('m-Y'));
